deploy:
  stage: deploy
  image: docker:20.10.16
  before_script:
    - apk add --no-cache curl bash
    - curl https://get.helm.sh/helm-v3.8.2-linux-amd64.tar.gz -o helm.tar.gz
    - tar -zxvf helm.tar.gz
    - mv linux-amd64/helm /usr/local/bin/helm
    - mkdir -p ~/.kube
    - echo "$KUBECONFIG" > ~/.kube/config  # Загружаем kubeconfig из переменной
    - helm repo add myrepo https://charts.example.com
    - helm repo update
  script:
    - helm install myapp myrepo/myapp-chart
