stages:
  - deploy

deploy_runner:
  stage: deploy
  script:
    - helm repo add gitlab https://charts.gitlab.io
    - helm repo update
    - echo "$KUBE_CONFIG" | base64 -d > /tmp/kubeconfig
    - kubectl --kubeconfig /tmp/kubeconfig create namespace cnrprod1737640949-team-83206 || true
    - helm install gitlab-runner gitlab/gitlab-runner -n cnrprod1737640949-team-83206 -f values.yaml
  only:
    - devops
  environment:
    KUBE_CONFIG: $KUBE_CONFIG
