image: docker:19.03.12

services:
  - docker:19.03.12-dind # Используем Docker-in-Docker для работы с Docker внутри контейнера

stages:
  - build
  - deploy

variables:
  DOCKER_IMAGE: "your-docker-image-name"
  DOCKER_TAG: "latest"
  KUBECONFIG: "/etc/kubernetes/config"    # Путь к kubeconfig файлу
  KUBECONFIG_CONTEXT: "your-context-name" # Контекст из kubeconfig файла
  KUBE_VERSION: "v1.23.3"                 # Версия Kubernetes
  HELM_VERSION: "v3.8.2"                  # Версия Helm
  YQ_VERSION: "4.15.1"                    # Версия yq
  TARGETOS: "linux"                       # Оп
