image: docker:27.0.3-dind
services:
  - docker:27.0.3-dind
variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""
  DOCKER_DRIVER: overlay2
  DOCKER_BUILDKIT: 1
  KUBERNETES_NAMESPACE: cnrprod1737640949-team-83206
  KUBECONFIG: "/builds/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME/.kube/config"  # Путь к kubeconfig
only:
  - main
before_script:
  - apk add --no-cache curl bash  # Устанавливаем необходимые пакеты для Helm
  - curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash  # Устанавливаем Helm
  - kubectl config use-context $KUBERNETES_NAMESPACE  # Устанавливаем правильный контекст для kubectl
  - kubectl config set-context --current --namespace=$KUBERNETES_NAMESPACE  # Устанавливаем namespace
  - kubectl get pods  # Проверка связи с кластером
script:
  - helm version  # Проверка версии Helm
  - helm repo add mychartrepo https://charts.example.com  # Добавление репозитория Helm
  - helm repo update  # Обновление репозиториев
  - helm upgrade --install my-release mychartrepo/mychart --namespace $KUBERNETES_NAMESPACE  # Установка/обновление чартов
tags:
  - runner
  - build
  - k8s
