stages:
  - detect
  - build

detect_docker:
  stage: detect
  image: "alpine:latest"  # Легкий образ для выполнения команд
  script:
    - echo "Checking Docker version..."
    - DOCKER_VERSION=$(docker --version)  # Получаем версию Docker
    - echo "Detected Docker Version: $DOCKER_VERSION"
    - echo "$DOCKER_VERSION" > docker_version.txt  # Сохраняем версию Docker в файл

build:
  stage: build
  image: "docker:latest"  # Docker-образ для сборки приложения
  tags:
    - runner
    - build
    - k8s
  script:
    - echo "Starting build with Docker..."
    - docker build -t myapp .  # Строим Docker-образ
    - docker push myapp:latest  # Отправляем образ на Docker Hub
