stages:
  - deploy

variables:
  KUBE_CONTEXT: "cnrprod1737640949-team-83206"
  HELM_KUBE_CONTEXT: "cnrprod1737640949-team-83206"
  HELM_HOME: "$CI_PROJECT_DIR/.helm"  # Путь к директории для хранения конфигурации Helm

before_script:
  - echo "$KUBECONFIG" > ~/.kube/config  # Сохранение kubeconfig в файл
  - kubectl config use-context $KUBE_CONTEXT  # Использование нужного контекста
  - helm repo add prometheus-community https://prometheus-community.github.io/helm-charts  # Добавление репозитория для Prometheus
  - helm repo update  # Обновление репозитория

deploy_helm:
  stage: deploy
  tags:
    - build
    - k8s
    - runner
  script:
    - echo "Deploying Prometheus using Helm in Kubernetes namespace $KUBE_CONTEXT"
    - helm upgrade --install prometheus prometheus-community/prometheus --namespace cnrprod1737640815-team-83210 --set prometheus.server.persistentVolume.enabled=false --set rbac.create=false --set kube-state-metrics.enabled=false
  only:
    - devops  # Указывайте нужную ветку
