stages:
  - build
  - deploy

# Переменные
variables:
  KUBE_CONTEXT: "cnrprod1737640949-team-83206"  # Ваш Kubernetes контекст
  KUBECONFIG: "/root/.kube/config"  # Путь до kubeconfig, если используется

# Кеширование Docker образов
cache:
  paths:
    - .docker

# Этап сборки (Build)
build:
  image: docker:20.10.16  # Используется Docker image
  stage: build
  services:
    - docker:dind
  script:
    - echo "Building Docker image"
    - docker build -t registry.gitlab.com/your-group/your-project:latest .
    - docker push registry.gitlab.com/your-group/your-project:latest
  only:
    - devops  # Выполняется только для ветки devops

# Этап деплоя (Deploy)
deploy:
  image: bitnami/kubectl:latest  # Используется образ с kubectl
  stage: deploy
  before_script:
    # Настройка Kubernetes контекста
    - kubectl config use-context $KUBE_CONTEXT
  script:
    # Применяем манифесты для деплоя
    - echo "Deployin
