image: docker:27.0.3-dind

services:
  - docker:27.0.3-dind

variables:
  DOCKER_HOST: tcp://docker:2375  # Используем HTTP-соединение
  DOCKER_TLS_CERTDIR: ""          # Отключаем сертификаты TLS
  KUBECONFIG: "/builds/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME/.kube/config"
  KUBECONFIG_CONTEXT: "cnrprod1737640949-team-83206"
  KUBERNETES_NAMESPACE: "cnrprod1737640949-team-83206"
  IMAGE_NAME: "your-image-name"   # Укажите имя образа
  REGISTRY: "docker.io"           # Укажите ваш Docker registry (например, Docker Hub)

stages:
  - build

build_with_dind_and_kaniko:
  stage: build
  script:
    - echo "Переход в директорию с Dockerfile..."
    - cd develop/backend/data-storage
    - echo "Сборка Docker-образа с помощью Kaniko..."
    - /kaniko/executor --context=dir://$(pwd) --dockerfile=Dockerfile --destination=$REGISTRY/$CI_PROJECT_NAMESPACE/$IMAGE_NAME:latest
    - echo "Образ собран и загружен в реестр!"
  only:
    - master  # или ваша нужная ветка
  tags:
    - build
    - runner
    - k8s
