stages:
  - deploy

variables:
  KUBE_CONTEXT: "cnrprod1737640949-team-83206"
  HELM_KUBE_CONTEXT: "cnrprod1737640949-team-83206"
  HELM_HOME: "$CI_PROJECT_DIR/.helm"  # Путь к директории для хранения конфигурации Helm

before_script:
  - echo "$KUBECONFIG" > ~/.kube/config  # Сохранение kubeconfig в файл
  - kubectl config use-context $KUBE_CONTEXT  # Использование нужного контекста
  - helm repo add stable https://charts.helm.sh/stable  # Добавление Helm репозитория
  - helm repo update  # Обновление репозитория

deploy_helm:
  stage: deploy
  tags:
    - build
    - k8s
  script:
    - echo "Deploying Helm in Kubernetes namespace $KUBE_CONTEXT"
    - helm install my-release stable/my-chart --namespace cnrprod1737640949-team-83206 --create-namespace
  only:
    - devops  # Указывайте нужную ветку
