stages:
  - build
  - push

variables:
  DOCKER_REGISTRY: "docker.io"
  DOCKER_IMAGE: "your-username/your-image-name"  # Укажите свой репозиторий на Docker Hub
  DOCKER_TAG: "latest"  # Укажите тег для вашего образа (например, latest или version)
  KUBE_VERSION: "v1.26.4"
  HELM_VERSION: "v3.11.3"

before_script:
  - apk add --no-cache curl

build_image:
  stage: build
  script:
    # Скачивание и установка helm и kubectl
    - curl -sSL https://get.helm.sh/helm-${HELM_VERSION}-linux-amd64.tar.gz | tar -xz -C /tmp
    - mv /tmp/linux-amd64/helm /usr/local/bin/helm
    - curl -sSL https://dl.k8s.io/release/${KUBE_VERSION}/bin/linux/amd64/kubectl -o /usr/local/bin/kubectl
    - chmod +x /usr/local/bin/helm /usr/local/bin/kubectl
    # Сборка Docker-образа
    - docker build -t $DOCKER_IMAGE:$DOCKER_TAG -f helm-kubectl-main/Dockerfile helm-kubectl-main

push_image:
  stage: push
  script:
    # Логин в Docker Hub
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    # Пуш Docker-образа
    - docker push $DOCKER_IMAGE:$DOCKER_TAG
  only:
    - devops  # Укажите ветку, для которой будет выполняться пуш
