stages:
  - build
  - kaniko-build
  - deploy

variables:
  DOCKER_REGISTRY: "git.codenrock.com:5050"
  IMAGE_PATH: "neo-hack-2025-1364/cnrprod1737640815-team-83210/razrabotka-telegram-bota-dlya-avtomatizacii-processa-sbora-zayavok-na-obuchenie-6462"
  IMAGE_TAG: "${DOCKER_REGISTRY}/${CI_PROJECT_NAMESPACE}/${CI_PROJECT_NAME}:latest"

# Этап сборки JAR-файла
build-telegram-bot-service:
  stage: build
  image: maven:3.9.4-eclipse-temurin-21
  tags:
    - runner
    - build
    - k8s
  only:
    - develop
  script:
    - cd develop/backend/data-storage
    - mvn clean package
    - ls -la target
  artifacts:
    paths:
      - develop/backend/data-storage/target/data-storage-1.0-SNAPSHOT-exec.jar
    expire_in: 1 week

# Этап сборки Docker-образа с использованием Kaniko
build-telegram-bot-service-docker:
  stage: kaniko-build
  image:
    name: gcr.io/kaniko-project/executor:v1.19.0-debug
    entrypoint: [""]  # Это нужно для корректного запуска Kaniko
  tags:
    - runner
    - build
    - k8s
  script:
    - /kaniko/executor --context "${CI_PROJECT_DIR}" --dockerfile "${CI_PROJECT_DIR}/develop/backend/data-storage/Dockerfile" --destination "${IMAGE_TAG}"
  artifacts:
    paths:
      - develop/backend/data-storage/target/data-storage-1.0-SNAPSHOT-exec.jar
    expire_in: 1 week

# Этап деплоя в Kubernetes
deploy-telegram-bot-service:
  stage: deploy
  image: bitnami/kubectl:latest
  tags:
    - runner
    - build
    - k8s
  only:
    - develop
  script:
    - echo "$KUBECONFIG_CONTENT" > kubeconfig
    - echo "KUBECONFIG file saved at:"; pwd; echo "/kube
