stages:
  - detect
  - build

detect_docker:
  stage: detect
  image: "alpine:latest"  # Легкий образ для запуска команды
  script:
    - echo "Checking Docker information..."
    - DOCKER_IMAGE=$(docker info --format '{{.Driver}}')  # Получаем информацию о драйвере Docker
    - echo "Detected Docker Driver: $DOCKER_IMAGE"
    - echo "Using $DOCKER_IMAGE to proceed with the build"
    - echo $DOCKER_IMAGE > docker_image.txt  # Сохраняем результат в файл для последующих шагов

build:
  stage: build
  image: $DOCKER_IMAGE  # Используем динамически определённый образ для сборк
  tags:
    - runner
    - build
    - k8s
  script:
    - echo "Building with the detected Docker image..."
    - docker build -t myapp .
    - docker push myapp:latest
