image: docker:19.03.12

services:
  - name: docker:19.03.12-dind
    alias: docker
    command:
      - "--tls=false"
      - "--host=tcp://0.0.0.0:2375"

stages:
  - build
  - deploy

variables:
  DOCKER_IMAGE: "your-docker-image-name"
  DOCKER_TAG: "latest"
  KUBECONFIG: "/etc/kubernetes/config"
  KUBE_VERSION: "v1.23.3"
  HELM_VERSION: "v3.8.2"
  YQ_VERSION: "4.15.1"
  DOCKER_TLS_CERTDIR: ""
  DOCKER_HOST: "tcp://docker:2375"

before_script:
  - apk add --no-cache curl
  - curl -sSL https://get.helm.sh/helm-${HELM_VERSION}-linux-amd64.tar.gz | tar -xz -C /tmp
  - mv /tmp/linux-amd64/helm /usr/local/bin/helm
  - curl -sSL https://dl.k8s.io/release/${KUBE_VERSION}/bin/linux/amd64/kubectl -o /usr/local/bin/kubectl
  - chmod +x /usr/local/bin/helm /usr/local/bin/kubectl
  - docker info

build:
  stage: build
  tags:
    - build
  script:
    - ls -l helm-kubectl-main
    - docker build -t $DOCKER_IMAGE:$DOCKER_TAG -f helm-kubectl-main/Dockerfile helm-kubectl-main
    - docker push $DOCKER_IMAGE:$DOCKER_TAG

deploy:
  stage: deploy
  tags:
    - k8s
  script:
    - kubectl --kubeconfig=$KUBECONFIG config use-context your-context-name
    - helm upgrade --install your-release-name ./helm-chart --kubeconfig=$KUBECONFIG
