image: my-helm-kubectl-docker:v3.17.0

stages:
  - build
  - deploy

variables:
  DOCKER_IMAGE: "your-docker-image-name"
  DOCKER_TAG: "latest"
  KUBECONFIG: "/etc/kubernetes/config"    # Путь к kubeconfig файлу
  KUBECONFIG_CONTEXT: "your-context-name" # Контекст из kubeconfig файла
  KUBE_VERSION: "v1.23.3"                 # Версия Kubernetes
  HELM_VERSION: "v3.8.2"                  # Версия Helm
  YQ_VERSION: "4.15.1"                    # Версия yq
  TARGETOS: "linux"                       # Операционная система
  TARGETARCH: "amd64"                     # Архитектура

before_script:
  # Нет необходимости устанавливать helm и kubectl, так как они уже есть в образе
  - echo "Using pre-installed helm and kubectl"

build:
  stage: build
  tags:
    - build
    - k8s
    - runner
  script:
    - docker build -t $DOCKER_IMAGE:$DOCKER_TAG .
    - docker push $DOCKER_IMAGE:$DOCKER_TAG

deploy:
  stage: deploy
  tags:
    - k8s
    - runner
  script:
    - kubectl --kubeconfig=$KUBECONFIG config use-context $KUBECONFIG_CONTEXT
    - helm upgrade --install your-release-name ./helm-chart --kubeconfig=$KUBECONFIG
