stages:
  - build

build:
  stage: build
  image: "docker:20.10.7" # Здесь указываем Docker образ с нужной версией
  tags:
    - runner
    - build
    - k8s
  script:
    - echo "Starting build with Docker..."
    - docker --version # Проверим, что Docker доступен
    - docker build -t myapp .
    - docker push myapp:latest
