image: gcr.io/kaniko-project/executor:latest  # Kaniko image

variables:
  DOCKER_CONFIG: /kaniko/.docker/  # Директория для конфигурации Docker
  IMAGE_NAME: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG  # Имя и тег образа, создаваемого Kaniko

stages:
  - build

build_with_kaniko:
  stage: build
  script:
    - echo "Настройка Docker аутентификации..."
      # Создаем конфиг для аутентификации в реестре Docker
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - echo "Сборка Docker-образа с помощью Kaniko..."
      # Kaniko выполняет сборку образа из указанного контекста и Dockerfile
    - /kaniko/executor --context $CI_PROJECT_DIR/develop/backend/data-storage \
                       --dockerfile $CI_PROJECT_DIR/develop/backend/data-storage/Dockerfile \
                       --destination $IMAGE_NAME
    - echo "Docker-образ успешно создан и загружен: $IMAGE_NAME"
  tags:
    - build  # Указываем подходящий тег для GitLab Runner
    - k8s    # Тег для Kubernetes Runner
