stages:
  - deploy

deploy:
  stage: deploy
  tags:
    - runner
    - build
    - k8s
  script:
    - echo "Deploying to Kubernetes with Argo CD"
    - export KUBECONFIG=$KUBECONFIG  # Используем KUBECONFIG из переменных GitLab
    - export KUBECONFIG_CONTEXT=$KUBECONFIG_CONTEXT  # Контекст для kubectl
    - kubectl config use-context $KUBECONFIG_CONTEXT  # Переключаем контекст Kubernetes
    - argocd app sync <app-name> --auth-token $ARGOCD_AUTH_TOKEN  # Деплой в Argo CD
