stages:
  - detect
  - build

detect_docker:
  stage: detect
  image: "alpine:latest"
  script:
    - echo "Checking Docker version..."
    - DOCKER_VERSION=$(docker --version)
    - echo "Detected Docker Version: $DOCKER_VERSION"
    - echo "$DOCKER_VERSION" > docker_version.txt

build:
  stage: build
  image: "docker:latest"
  tags:
    - runner
    - build
    - k8s
  script:
    - echo "Starting build with Docker..."
    - docker build -t myapp .
    - docker push myapp:latest
