image: docker:19.03.12-dind

services:
  - docker:19.03.12-dind

variables:
  DOCKER_HOST: tcp://docker:2375  # Подключение через HTTP
  DOCKER_TLS_CERTDIR: ""          # Отключение использования TLS сертификатов
  KUBECONFIG: "/builds/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME/.kube/config"
  KUBECONFIG_CONTEXT: "cnrprod1737640949-team-83206"
  IMAGE_NAME: "your-image-name"
  REGISTRY: "docker.io"

stages:
  - build

build_with_dind_and_kaniko:
  stage: build
  script:
    - echo "Переход в директорию с Dockerfile..."
    - cd develop/backend/data-storage
    - echo "Сборка Docker-образа с помощью Kaniko..."
    - /kaniko/executor --context=dir://$(pwd) --dockerfile=Dockerfile --destination=$REGISTRY/$CI_PROJECT_NAMESPACE/$IMAGE_NAME:latest
    - echo "Образ собран и загружен в реестр!"
  only:
    - master  # или ваша нужная ветка
  tags:
    - build
    - runner
    - k8s
