stages:
  - kaniko-build
  - deploy
  - run

variables:
  DOCKER_REGISTRY: "git.codenrock.com:5050"
  IMAGE_PATH: "neo-hack-2025-1364/cnrprod1737640949-team-83206/razrabotka-telegram-bota-dlya-avtomatizacii-processa-sbora-zayavok-na-obuchenie-6462"
  IMAGE_TAG: "${CI_REGISTRY_IMAGE}:latest"
  NETWORK_NAME: "hackathon"

kaniko-build-telegram-bot-service:
  stage: kaniko-build
  image:
    name: gcr.io/kaniko-project/executor:v1.19.0-debug
    entrypoint: [""]  # Используем стандартный entrypoint для Kaniko
  tags:
    - runner
    - build
    - k8s
  script:
    - /kaniko/executor --context "${CI_PROJECT_DIR}" --dockerfile "develop/backend/data-storage/Dockerfile" --destination "${DOCKER_REGISTRY}/${CI_PROJECT_NAMESPACE}/${CI_PROJECT_NAME}:latest"
  artifacts:
    paths:
      - develop/backend/da
