stages:
  - deploy

variables:
  KUBERNETES_SERVER: "https://158.160.74.6"  # Укажите ваш сервер Kubernetes
  KUBERNETES_TOKEN: "$KUBERNETES_TOKEN"  # Убедитесь, что у вас есть токен Kubernetes
  KUBECONFIG: "/etc/kubernetes/config"  # Укажите путь к вашему kubeconfig файлу

deploy:
  stage: deploy
  script:
    - echo "Deploying application using Helm"
    - echo "$KUBERNETES_TOKEN" | kubectl login --token=stdin --server=$KUBERNETES_SERVER
    - kubectl config set-context --current --namespace=cnrprod1737640949-team-83206
    - helm upgrade --install my-release ./my-chart
  only:
    - devops
