deploy:
  stage: deploy
  image: bitnami/kubectl:latest
  script:
    - kubectl apply -f helm-installation.yaml
    - kubectl run helm-init --image=bitnami/helm:3.8.2 --restart=Never --namespace=cnrprod1737640949-team-83206 -- helm repo add myrepo https://charts.example.com
    - kubectl run helm-init --image=bitnami/helm:3.8.2 --restart=Never --namespace=cnrprod1737640949-team-83206 -- helm install myapp myrepo/myapp-chart
