stages:
  - install-argocd

install-argocd:
  stage: install-argocd
  tags:
    - runner
    - build
    - k8s
  script:
    - echo "$KUBECONFIG" > /tmp/kubeconfig
    - export KUBECONFIG=/tmp/kubeconfig
    - kubectl version --client
    - kubectl create namespace argocd || true
    - kubectl apply -n argocd -f https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
    - kubectl wait --for=condition=available --timeout=600s deployment/argocd-server -n argocd
    - echo "Argo CD installed successfully!"
