stages:
  - setup
  - deploy

variables:
  HELM_VERSION: "v3.8.0"  # Укажите версию Helm, которую хотите установить

before_script:
  - echo "Setting up kubectl and Helm"
  - kubectl config use-context ${KUBE_CONTEXT}  # Убедитесь, что контекст настроен в переменных окружения

setup_helm:
  stage: setup
  script:
    - curl -sSL https://get.helm.sh/helm-${HELM_VERSION}-linux-amd64.tar.gz | tar xz
    - mv linux-amd64/helm /usr/local/bin/helm
    - helm version  # Проверка версии Helm

deploy_app:
  stage: deploy
  script:
    - helm repo add myrepo https://charts.example.com
    - helm repo update
    - helm upgrade --install my-release myrepo/mychart --namespace ${KUBE_NAMESPACE}

