stages:
  - deploy

deploy_argo_cd:
  stage: deploy
  tags:
    - k8s
  script:
    - kubectl config use-context $KUBE_CONTEXT
    - kubectl create namespace argocd || true
    - kubectl apply -n argocd -f https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
    - kubectl -n argocd rollout status deployment/argocd-server
  only:
    - devops
