stages:
  - build
  - kaniko-build
  - deploy

variables:
  DOCKER_REGISTRY: "git.codenrock.com:5050"
  IMAGE_PATH: "neo-hack-2025-1364/cnrprod1737640949-team-83206/razrabotka-telegram-bota-dlya-avtomatizacii-processa-sbora-zayavok-na-obuchenie-6462"
  IMAGE_TAG: "${CI_REGISTRY_IMAGE}:latest"

build-telegram-bot-service:
  stage: build
  image: maven:3.9.4-eclipse-temurin-21
  tags:
    - runner
    - build
    - k8s
  only:
    - develop
  script:
    - cd develop/telegram-bot-service
    - mvn clean package
    - ls -la target
  artifacts:
    paths:
      - develop/telegram-bot-service/target/*.jar
    expire_in: 1 week

kaniko-build:
  stage: kaniko-build
  image:
    name: gcr.io/kaniko-project/executor:v1.19.0-debug
    entrypoint: [""]
  tags:
    - runner
    - build
    - k8s
  script:
    - /kaniko/executor --context "${CI_PROJECT_DIR}/develop/telegram-bot-service" --dockerfile "${CI_PROJECT_DIR}/develop/telegram-bot-service/Dockerfile" --destination "${DOCKER_REGISTRY}/${IMAGE_PATH}:${CI_COMMIT_REF_NAME}"
  dependencies:
    - build-telegram-bot-service
  artifacts:
    paths:
      - develop/telegram-bot-service/target/*.jar
    expire_in: 1 week

deploy-telegram-bot-service:
  stage: deploy
  image: bitnami/kubectl:latest
  tags:
    - runner
    - build
    - k8s
  only:
    - develop
  script:
    - echo "$KUBECONFIG_CONTENT" > kubeconfig
    - export KUBECONFIG=$(pwd)/kubeconfig
    - kubectl apply -f devops/k8s/telegram-bot-service-deployment.yaml --namespace=cnrprod1737640949-team-83206
