apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: cnrprod1737640949-team-83206
  name: argocd-role
rules:
- apiGroups: [""]
  resources: ["pods", "services", "configmaps", "secrets"]
  verbs: ["get", "list", "watch", "create", "update", "delete"]
- apiGroups: ["apps"]
  resources: ["deployments", "replicasets"]
  verbs: ["get", "list", "watch", "create", "update", "delete"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: cnrprod1737640949-team-83206
  name: argocd-rolebinding
subjects:
- kind: ServiceAccount
  name: cnrprod1737640949-team-83206
  namespace: cnrprod1737640949-team-83206
roleRef:
  kind: Role
  name: argocd-role
  apiGroup: rbac.authorization.k8s.io
