stages:
  - build
  - deploy

variables:
  DOCKER_IMAGE: "your-docker-image-name"
  DOCKER_TAG: "latest"
  KUBECONFIG: "/etc/kubernetes/config"    # Путь к kubeconfig файлу
  KUBECONFIG_CONTEXT: "your-context-name" # Контекст из kubeconfig файла

before_script:
  - apk add --no-cache curl bash git openssh
  - curl -sSL https://get.helm.sh/helm-v3.8.2-linux-amd64.tar.gz | tar -xz -C /tmp
  - mv /tmp/linux-amd64/helm /usr/local/bin/helm
  - curl -sSL https://dl.k8s.io/release/v1.23.3/bin/linux/amd64/kubectl -o /usr/local/bin/kubectl
  - chmod +x /usr/local/bin/helm /usr/local/bin/kubectl

build:
  stage: build
  tags:
    - build
    - k8s
    - runner
  script:
    - docker build -t $DOCKER_IMAGE:$DOCKER_TAG .
    - docker push $DOCKER_IMAGE:$DOCKER_TAG

deploy:
  stage: deploy
  tags:
    - k8s
    - runner
  script:
    - kubectl --kubeconfig=$KUBECONFIG config use-context $KUBECONFIG_CONTEXT
    - helm upgrade --install your-release-name ./helm-chart --kubeconfig=$KUBECONFIG
