gitlabUrl: https://gitlab.com/
runnerRegistrationToken: "glrt-XjWV8kybb97cz4rRsRjf"  # Укажи свой регистрационный токен
namespace: cnrprod1737640949-team-83206
rbac:
  create: true
runners:
  tags:
    - runner
    - build
    - k8s
  config: |
    [[runners]]
      name = "k8s-runner"
      url = "https://gitlab.com/"
      token = "your-token-here"
      executor = "kubernetes"
      [runners.kubernetes]
        image = "alpine:latest"
        namespace = "cnrprod1737640949-team-83206"
        pollTimeout = 600
