server:
  port: 9090

bot:
  name: ${TG_BOT_NAME:hakatonTG_bot}
  token: ${TG_BOT_TOKEN:7083829801:AAGiKATQRCVmbz5g8XYdV7P5kk174qwVna8}

logging:
  level:
    ru.neostudy.apiservice: DEBUG

storage:
  serverUrl: http://localhost:8080
  get-user-by-email-uri: /data-storage/getUserByEmail/{email}
  get-user-by-telegram-uri: /data-storage/getUserByTelegramId/{telegramId}
  save-user-uri: /data-storage/saveUser
  getCoursesUri: /data-storage/getCourses


